stages:
  - static_analysis
  - build_n_test

variables:
  PROJECT_NAME: nautilus
  ENABLE_CDASH: true
  ENABLED_CLUSTERS: "darwin,rocinante,venado,rzansel,rzvernal,rzadams"
  # Use this variable if there is a xcap/deployment MR you want to use instead
  # Note: only change the MR number, the date is effectively the "Spack version"
  #PROJECT_SPACK_ENV_VERSION: mr/68/2024-10-15

include:
 - .gitlab/common.yml

format:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_mr_only_job, .clang_format]

pages_check:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_mr_only_job, .build_docs]

pages:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_default_branch_only_job, .build_docs]
  artifacts:
    paths:
      - public

prereq_offline_deps:
  stage: build_n_test
  extends: [.ascgit_job]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs: []
  script:
    - mkdir extern
    - git clone --bare https://gitlab-ci-token:${CI_JOB_TOKEN}@re-git.lanl.gov/xcap/oss/ports-of-call.git extern/ports-of-call.git
  artifacts:
    expire_in: 2 days
    paths:
      - extern

# Spack environments are defined in
# https://re-git.lanl.gov/xcap/deployment/-/tree/xcap-spack-env/systems
# for each system and for each XCAP project.
#
# The project configuration can be found at the top of
# .gitlab/build_and_test.sh.
#
# Each environment is uniquely identified by
# ${SYSTEM_NAME}/${PROJECT_GROUP}/${PROJECT_NAME}/${SPACK_ENV_NAME}
#
# For creating a new custom environment for testing use the special
# 'custom-spec' or 'custom-file` environments.
#
# The 'custom-spec` environment allows you specify an arbitrary Spack spec to
# be added to a system-specific empty Spack environment. Use the SPACK_ENV_SPEC
# environment variable to define the spec you want to add.

# The 'custom-file` environment allows you to manually define an environment
# from scratch.  Use the SPACK_ENV_FILE environment variable to specify the
# path to the YAML file you want to use. Note, the environment will be placed
# in ${SYSTEM_NAME}/${PROJECT_GROUP}/${PROJECT_NAME}/custom-file/spack.yaml and
# can therefore make relative includes to common configuration files.
darwin_custom_gcc:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: custom-spec
    SPACK_ENV_SPEC: "nautilus@main%gcc +test build_type=Release ^[virtuals=mpi] openmpi"
    # SUBMIT_TO_CDASH is false by default

darwin_openmpi_gcc:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: openmpi-gcc
    SUBMIT_TO_CDASH: "${ENABLE_CDASH}"

darwin_openmpi_gcc_nokokkos:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: openmpi-gcc-nokokkos
    SUBMIT_TO_CDASH: "${ENABLE_CDASH}"

darwin_mpich_cuda_volta_gcc:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: mpich-cuda-volta-gcc
    SCHEDULER_PARAMETERS: "-N 1 --qos=debug -p volta-x86 -C cpu_family:haswell"
    SUBMIT_TO_CDASH: "${ENABLE_CDASH}"

darwin_mpich_cuda_volta_gcc_nokokkos:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: mpich-cuda-volta-gcc-nokokkos
    SCHEDULER_PARAMETERS: "-N 1 --qos=debug -p volta-x86 -C cpu_family:haswell"
    SUBMIT_TO_CDASH: "${ENABLE_CDASH}"

darwin_mpich_cuda_ampere_gcc:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: mpich-cuda-ampere-gcc
    SCHEDULER_PARAMETERS: "-N 1 --qos=debug -p shared-gpu-ampere"
    SUBMIT_TO_CDASH: "${ENABLE_CDASH}"

darwin_mpich_rocm_mi250_gcc:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: mpich-rocm-gfx90a-gcc
    SCHEDULER_PARAMETERS: "-N 1 --qos=debug -p shared-gpu-amd-mi250"
    SUBMIT_TO_CDASH: "${ENABLE_CDASH}"

darwin_mpich_rocm_mi250_gcc_nokokkos:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: mpich-rocm-gfx90a-gcc-nokokkos
    SCHEDULER_PARAMETERS: "-N 1 --qos=debug -p shared-gpu-amd-mi250"
    SUBMIT_TO_CDASH: "${ENABLE_CDASH}"

rocinante_craympich_gcc:
  extends: [.ascgit_job, .rocinante_job, .rocinante_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: craympich-gcc
    SUBMIT_TO_CDASH: false
    BUILD_WITH_CTEST: "${ENABLE_CDASH}"
    SUBMIT_ON_ERROR: false          # Venado nodes don't have network access, don't try to send from compute node
    SUBMIT_AFTER: "${ENABLE_CDASH}" # after_script runs on a network connected system

rocinante_craympich_intel:
  extends: [.ascgit_job, .rocinante_job, .rocinante_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: craympich-intel
    SUBMIT_TO_CDASH: false
    BUILD_WITH_CTEST: "${ENABLE_CDASH}"
    SUBMIT_ON_ERROR: false          # Venado nodes don't have network access, don't try to send from compute node
    SUBMIT_AFTER: "${ENABLE_CDASH}" # after_script runs on a network connected system

venado_craympich_cuda_gracehopper_gcc:
  extends: [.ascgit_job, .venado_job, .venado_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: craympich-cuda-gracehopper-gcc
    SUBMIT_TO_CDASH: false
    BUILD_WITH_CTEST: "${ENABLE_CDASH}"
    SUBMIT_ON_ERROR: false          # Venado nodes don't have network access, don't try to send from compute node
    SUBMIT_AFTER: "${ENABLE_CDASH}" # after_script runs on a network connected system

rzansel_spectrummpi_cuda_volta_gcc:
  extends: [.ascgit_job, .rzansel_job, .rzansel_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: spectrummpi-cuda-volta-gcc
    SUBMIT_TO_CDASH: false              # disable CDash submission, since LLNL systems can't reach them
    BUILD_WITH_CTEST: "${ENABLE_CDASH}" # but do build with CTest to create the necessary files
    SUBMIT_ON_ERROR: false              # no network access, don't try to send from compute node
    SUBMIT_AFTER: false                 # submit host also doesn't have access to CDash server
    CREATE_SUBMIT_ARTIFACT: "${ENABLE_CDASH}" # archive results

rzansel_spectrummpi_cuda_volta_xl:
  extends: [.ascgit_job, .rzansel_job, .rzansel_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: spectrummpi-cuda-volta-xl
    SUBMIT_TO_CDASH: false              # disable CDash submission, since LLNL systems can't reach them
    BUILD_WITH_CTEST: "${ENABLE_CDASH}" # but do build with CTest to create the necessary files
    SUBMIT_ON_ERROR: false              # no network access, don't try to send from compute node
    SUBMIT_AFTER: false                 # submit host also doesn't have access to CDash server
    CREATE_SUBMIT_ARTIFACT: "${ENABLE_CDASH}" # archive results

rzvernal_craympich_rocm_mi250_gcc:
  extends: [.ascgit_job, .rzvernal_job, .rzvernal_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: craympich-rocm-gfx90a-gcc
    SUBMIT_TO_CDASH: false              # disable CDash submission, since LLNL systems can't reach them
    BUILD_WITH_CTEST: "${ENABLE_CDASH}" # but do build with CTest to create the necessary files
    SUBMIT_ON_ERROR: false              # no network access, don't try to send from compute node
    SUBMIT_AFTER: false                 # submit host also doesn't have access to CDash server
    CREATE_SUBMIT_ARTIFACT: "${ENABLE_CDASH}" # archive results

rzadams_craympich_rocm_mi300_gcc:
  extends: [.ascgit_job, .rzadams_job, .rzadams_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: craympich-rocm-gfx942-gcc
    SUBMIT_TO_CDASH: false              # disable CDash submission, since LLNL systems can't reach them
    BUILD_WITH_CTEST: "${ENABLE_CDASH}" # but do build with CTest to create the necessary files
    SUBMIT_ON_ERROR: false              # no network access, don't try to send from compute node
    SUBMIT_AFTER: false                 # submit host also doesn't have access to CDash server
    CREATE_SUBMIT_ARTIFACT: "${ENABLE_CDASH}" # archive results

# collect job results from RZansel and submit them to CDash
post_rzansel_results_to_cdash:
  extends: [.post_results_to_cdash]
  allow_failure: true
  rules:
    - if: $ENABLE_CDASH == "true" && $ENABLED_CLUSTERS =~ /rzansel/ && $GITLAB_USER_LOGIN =~ $RZANSEL_USERS && $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $ENABLE_CDASH == "true" && $ENABLED_CLUSTERS =~ /rzansel/ && $GITLAB_USER_LOGIN =~ $RZANSEL_USERS && $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - if: $ENABLE_CDASH == "true" && $ENABLED_CLUSTERS =~ /rzansel/ && $GITLAB_USER_LOGIN =~ $RZANSEL_USERS && $CI_PIPELINE_SOURCE == "web"
      when: always
    - if: $ENABLE_CDASH == "true" && $ENABLED_CLUSTERS =~ /rzansel/ && $GITLAB_USER_LOGIN =~ $RZANSEL_USERS && $CI_PIPELINE_SOURCE == "push"
      when: always
  needs:
    - rzansel_spectrummpi_cuda_volta_gcc
    - rzansel_spectrummpi_cuda_volta_xl

# collect job results from RZvernal and submit them to CDash
post_rzvernal_results_to_cdash:
  extends: [.post_results_to_cdash]
  allow_failure: true
  rules:
    - if: $ENABLE_CDASH == "true" && $ENABLED_CLUSTERS =~ /rzvernal/ && $GITLAB_USER_LOGIN =~ $RZVERNAL_USERS && $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $ENABLE_CDASH == "true" && $ENABLED_CLUSTERS =~ /rzvernal/ && $GITLAB_USER_LOGIN =~ $RZVERNAL_USERS && $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - if: $ENABLE_CDASH == "true" && $ENABLED_CLUSTERS =~ /rzvernal/ && $GITLAB_USER_LOGIN =~ $RZVERNAL_USERS && $CI_PIPELINE_SOURCE == "web"
      when: always
    - if: $ENABLE_CDASH == "true" && $ENABLED_CLUSTERS =~ /rzvernal/ && $GITLAB_USER_LOGIN =~ $RZVERNAL_USERS && $CI_PIPELINE_SOURCE == "push"
      when: always
  needs:
    - rzvernal_craympich_rocm_mi250_gcc

# collect job results from RZadams and submit them to CDash
post_rzadams_results_to_cdash:
  extends: [.post_results_to_cdash]
  allow_failure: true
  rules:
    - if: $ENABLE_CDASH == "true" && $ENABLED_CLUSTERS =~ /rzadams/ && $GITLAB_USER_LOGIN =~ $RZADAMS_USERS && $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $ENABLE_CDASH == "true" && $ENABLED_CLUSTERS =~ /rzadams/ && $GITLAB_USER_LOGIN =~ $RZADAMS_USERS && $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - if: $ENABLE_CDASH == "true" && $ENABLED_CLUSTERS =~ /rzadams/ && $GITLAB_USER_LOGIN =~ $RZADAMS_USERS && $CI_PIPELINE_SOURCE == "web"
      when: always
    - if: $ENABLE_CDASH == "true" && $ENABLED_CLUSTERS =~ /rzadams/ && $GITLAB_USER_LOGIN =~ $RZADAMS_USERS && $CI_PIPELINE_SOURCE == "push"
      when: always
  needs:
    - rzadams_craympich_rocm_mi300_gcc
