stages:
  - static_analysis
  - build_n_test

variables:
  PROJECT_NAME: nautilus
  PROJECT_GROUP: oss
  ENABLE_CDASH: true

include:
 - .gitlab/common.yml

prereq_offline_deps:
  stage: static_analysis
  extends: [.ascgit_job, .darwin_job]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs: []
  script:
   - source .gitlab/download_prereqs.sh
  artifacts:
    expire_in: 2 days
    paths:
      - extern

format:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_mr_only_job, .clang_format]
  needs: ["prereq_offline_deps"]

pages_check:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_mr_only_job, .build_docs]
  needs: ["prereq_offline_deps"]

pages:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_default_branch_only_job, .build_docs]
  needs: ["prereq_offline_deps"]
  artifacts:
    paths:
      - public

# Spack environments are defined in
# https://re-git.lanl.gov/xcap/deployment/-/tree/develop/environments
# for each system and for each XCAP project.
#
# Each environment is uniquely identified by
# ${SYSTEM_NAME}/${PROJECT_GROUP}/${PROJECT_NAME}/${SPACK_ENV_NAME}
#
darwin_custom_gcc:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: custom-spec
    SPACK_ENV_SPEC: "nautilus@main%gcc +test build_type=Release ^[virtuals=mpi] openmpi"
    # SUBMIT_TO_CDASH is false by default

darwin_openmpi_gcc:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: openmpi-gcc
    SUBMIT_TO_CDASH: "${ENABLE_CDASH}"

darwin_openmpi_gcc_debug:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: openmpi-gcc-debug
    SUBMIT_TO_CDASH: "${ENABLE_CDASH}"

darwin_openmpi_gcc_nokokkos:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: openmpi-gcc-nokokkos
    SUBMIT_TO_CDASH: "${ENABLE_CDASH}"

darwin_openmpi_gcc_nokokkos_debug:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: openmpi-gcc-nokokkos-debug
    SUBMIT_TO_CDASH: "${ENABLE_CDASH}"

darwin_mpich_cuda_volta_gcc:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: mpich-cuda-volta-gcc
    SCHEDULER_PARAMETERS: "-N 1 --qos=debug -p volta-x86 -C cpu_family:haswell"
    SUBMIT_TO_CDASH: "${ENABLE_CDASH}"

darwin_mpich_cuda_volta_gcc_nokokkos:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: mpich-cuda-volta-gcc-nokokkos
    SCHEDULER_PARAMETERS: "-N 1 --qos=debug -p volta-x86 -C cpu_family:haswell"
    SUBMIT_TO_CDASH: "${ENABLE_CDASH}"

darwin_mpich_cuda_ampere_gcc:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: mpich-cuda-ampere-gcc
    SCHEDULER_PARAMETERS: "-N 1 --qos=debug -p shared-gpu-ampere"
    SUBMIT_TO_CDASH: "${ENABLE_CDASH}"

darwin_mpich_rocm_mi250_gcc:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: mpich-rocm-gfx90a-gcc
    SCHEDULER_PARAMETERS: "-N 1 --qos=debug -p shared-gpu-amd-mi250"
    SUBMIT_TO_CDASH: "${ENABLE_CDASH}"

darwin_mpich_rocm_mi250_gcc_nokokkos:
  extends: [.ascgit_job, .darwin_job, .darwin_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: mpich-rocm-gfx90a-gcc-nokokkos
    SCHEDULER_PARAMETERS: "-N 1 --qos=debug -p shared-gpu-amd-mi250"
    SUBMIT_TO_CDASH: "${ENABLE_CDASH}"

rocinante_craympich_gcc:
  extends: [.ascgit_job, .rocinante_job, .rocinante_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: craympich-gcc
    SUBMIT_TO_CDASH: false
    BUILD_WITH_CTEST: "${ENABLE_CDASH}"
    SUBMIT_ON_ERROR: false          # nodes don't have network access, don't try to send from compute node
    SUBMIT_AFTER: "${ENABLE_CDASH}" # after_script runs on a network connected system

rocinante_craympich_intel:
  extends: [.ascgit_job, .rocinante_job, .rocinante_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: craympich-intel
    SUBMIT_TO_CDASH: false
    BUILD_WITH_CTEST: "${ENABLE_CDASH}"
    SUBMIT_ON_ERROR: false          # nodes don't have network access, don't try to send from compute node
    SUBMIT_AFTER: "${ENABLE_CDASH}" # after_script runs on a network connected system

venado_craympich_cuda_gracehopper_gcc:
  extends: [.ascgit_job, .venado_job, .venado_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: craympich-cuda-gracehopper-gcc
    SUBMIT_TO_CDASH: false
    BUILD_WITH_CTEST: "${ENABLE_CDASH}"
    SUBMIT_ON_ERROR: false          # Venado nodes don't have network access, don't try to send from compute node
    SUBMIT_AFTER: "${ENABLE_CDASH}" # after_script runs on a network connected system

rzvernal_craympich_rocm_mi250_gcc:
  extends: [.ascgit_job, .rzvernal_job, .rzvernal_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: craympich-rocm-gfx90a-gcc
    SUBMIT_TO_CDASH: false
    BUILD_WITH_CTEST: "${ENABLE_CDASH}"
    SUBMIT_ON_ERROR: false          # nodes don't have network access, don't try to send from compute node
    SUBMIT_AFTER: "${ENABLE_CDASH}" # after_script runs on a network connected system

rzadams_craympich_rocm_mi300_gcc:
  extends: [.ascgit_job, .rzadams_job, .rzadams_regular_job, .build_and_test]
  needs:
    - prereq_offline_deps
  variables:
    SPACK_ENV_NAME: craympich-rocm-gfx942-gcc
    SUBMIT_TO_CDASH: false
    BUILD_WITH_CTEST: "${ENABLE_CDASH}"
    SUBMIT_ON_ERROR: false          # nodes don't have network access, don't try to send from compute node
    SUBMIT_AFTER: "${ENABLE_CDASH}" # after_script runs on a network connected system
